using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NxMcpPlugin.Protocol;
using NxMcpPlugin.Tools;

namespace NxMcpPlugin
{
    /// <summary>
    /// TCP JSON line protocol server
    ///
    /// Listens on localhost:1977, handles requests from MCP Server.
    /// Each connection handled independently, supports pipeline reuse.
    ///
    /// Protocol:
    ///   Request:  JSON one line \n
    ///   Response: JSON one line \n
    ///
    /// Registry pattern:
    ///   - Use Dictionary to store method handlers
    ///   - Support dynamically adding new methods (auto-generated by sdk-forge)
    ///   - Eliminate hardcoded switch statements
    ///
    /// Supported methods:
    ///   ping              → Health check
    ///   get_selection     → Get current selection
    ///   get_model_summary → Get model summary
    ///   tool              → Execute tool (unified entry point)
    ///   list_tools        → List available tools
    ///   measure           → Measure area/volume/distance
    ///   list_features     → List feature tree
    ///   modify_expression → Modify parameter expression
    ///   export            → Export STEP/IGES
    ///   undo              → Undo last step
    ///   get_parameters    → Get expression list
    /// </summary>
    public class TcpServer
    {
        private dynamic _session;
        private dynamic _ui;
        private SelectionMonitor _monitor;
        private TcpListener _listener;
        private volatile bool _running;
        public bool IsRunning { get { return _running; } }
        private ToolRegistry _toolRegistry;

        /// <summary>
        /// Engineering rules engine — performs process knowledge checks on tool parameters
        /// (hole clearance / wall thickness / depth-to-diameter ratio / thread matching etc.).
        /// Rule table (15 rules) in rules/rules_config.json, deployed alongside DLL to startup\rules\.
        ///
        /// ★ Only hints, never blocks: check results uniformly attached as data.rule_check in response.
        ///   Even if rule verdict is error level, it's only hint text — never changes success, never rejects execution.
        ///   Reason: rules contain items dependent on geometry estimation;
        ///   strict enforcement would harm legitimate operations
        ///   (e.g. rule-extrude-positive-distance requires positive extrusion, but NX allows negative extrusion).
        /// </summary>
        private Rules.RuleEngine _rules;

        /// <summary>
        /// Maximum message length limit (1MB) — prevent memory exhaustion attacks
        /// </summary>
        private const int MAX_MESSAGE_LENGTH = 1024 * 1024;

        /// <summary>
        /// Method handler registry
        /// Key: Method name (e.g. "ping", "tool")
        /// Value: Handler function (receives id and rawParams, returns JSON string)
        /// </summary>
        private Dictionary<string, Func<int, JToken, string>> _methodHandlers;

        public TcpServer(dynamic session, dynamic ui, SelectionMonitor monitor)
        {
            _session = session;
            _ui = ui;
            _monitor = monitor;

            // Initialize tool registry
            _toolRegistry = ToolRegistry.Instance;
            _toolRegistry.RegisterAll();
            Log(string.Format("Tool registry initialized: {0} tools", _toolRegistry.ToolCount));

            // Rule engine — read-only hints, consumption point is rule_check in HandleTool
            _rules = new Rules.RuleEngine(_session);

            // Initialize method registry
            _methodHandlers = new Dictionary<string, Func<int, JToken, string>>();

            // Core methods
            RegisterMethod("ping", HandlePing);
            RegisterMethod("get_selection", HandleGetSelection);
            RegisterMethod("get_model_summary", HandleGetModelSummary);
            RegisterMethod("tool", HandleTool);
            RegisterMethod("list_tools", HandleListTools);

            // Methods implemented via NX API
            RegisterMethod("measure", HandleMeasure);
            RegisterMethod("list_features", HandleListFeatures);
            RegisterMethod("modify_expression", HandleModifyExpression);
            RegisterMethod("export", HandleExport);
            RegisterMethod("undo", HandleUndo);
            RegisterMethod("get_parameters", HandleGetParameters);

            Log(string.Format("Method registry initialized: {0} methods", _methodHandlers.Count));
        }

        /// <summary>
        /// Register new method handler
        ///
        /// Usage:
        ///   server.RegisterMethod("my_method", MyHandler);
        ///
        /// Code auto-generated by sdk-forge:
        ///   server.RegisterMethod("new_method", GeneratedHandler);
        /// </summary>
        /// <param name="method">Method name (e.g. "create_pocket")</param>
        /// <param name="handler">Handler function</param>
        public void RegisterMethod(string method, Func<int, JToken, string> handler)
        {
            if (string.IsNullOrEmpty(method))
                throw new ArgumentException("Method name cannot be empty");

            if (handler == null)
                throw new ArgumentNullException("handler");

            _methodHandlers[method] = handler;
        }

        /// <summary>
        /// Get list of registered methods
        /// </summary>
        public IEnumerable<string> GetRegisteredMethods()
        {
            return _methodHandlers.Keys;
        }

        /// <summary>
        /// Check if method is registered
        /// </summary>
        public bool HasMethod(string method)
        {
            return _methodHandlers.ContainsKey(method);
        }

        /// <summary>
        /// Start TCP listening
        /// </summary>
        /// <param name="host">Bind address, localhost only</param>
        /// <param name="port">Port, default 1977</param>
        public void Start(string host = "127.0.0.1", int port = 1977)
        {
            _listener = new TcpListener(IPAddress.Parse(host), port);
            _listener.Start();
            _running = true;

            Log(string.Format("TCP service started: {0}:{1}", host, port));

            // Connection acceptance loop — each HandleClient round is synchronous
            // Simple scenario handles one connection at a time (can be changed to async later)
            while (_running)
            {
                try
                {
                    var client = _listener.AcceptTcpClient();
                    Log(string.Format("Client connected: {0}", client.Client.RemoteEndPoint));
                    // Use thread pool to avoid blocking
                    System.Threading.ThreadPool.QueueUserWorkItem(_ =>
                    {
                        try { HandleClient(client); }
                        catch (Exception ex) { Log(string.Format("Client exception: {0}", ex.Message)); }
                        finally
                        {
                            try { client.Close(); } catch { }
                            Log("Client disconnected");
                        }
                    });
                }
                catch (SocketException)
                {
                    if (_running)
                        throw;
                    // Normal shutdown
                }
                catch (Exception ex)
                {
                    Log(string.Format("Accept connection exception: {0}", ex.Message));
                }
            }
        }

        /// <summary>
        /// Handle single client — line protocol
        /// </summary>
        private void HandleClient(TcpClient client)
        {
            try
            {
                var stream = client.GetStream();
                var encoding = new UTF8Encoding(false);

                // Simple byte-level line reading, avoid StreamReader blocking or BOM writing
                var buffer = new List<byte>();
                int b;
                while ((b = stream.ReadByte()) != -1)
                {
                    if (b == '\n')
                    {
                        var line = encoding.GetString(buffer.ToArray()).TrimEnd('\r');
                        buffer.Clear();
                        if (string.IsNullOrWhiteSpace(line)) continue;

                        Log(string.Format("Received raw message: {0}", line));
                        string response;
                        try
                        {
                            response = ProcessMessage(line);
                        }
                        catch (Exception ex)
                        {
                            response = JsonProtocol.Serialize(new ResponseMessage { Id = 0, Error = "Processing exception: " + ex.Message });
                            Log(string.Format("ProcessMessage exception: {0}\n{1}", ex.Message, ex.StackTrace));
                        }

                        var respBytes = encoding.GetBytes(response + "\n");
                        stream.Write(respBytes, 0, respBytes.Length);
                        stream.Flush();
                        Log(string.Format("Sent {0} bytes response", respBytes.Length));
                    }
                    else
                    {
                        // Safety check: limit message length to prevent memory exhaustion
                        if (buffer.Count >= MAX_MESSAGE_LENGTH)
                        {
                            Log(string.Format("Message length exceeds limit ({0} bytes), discarded", MAX_MESSAGE_LENGTH));
                            buffer.Clear();
                            // Read until newline, discard remaining data
                            while ((b = stream.ReadByte()) != -1 && b != '\n') { }
                            continue;
                        }
                        buffer.Add((byte)b);
                    }
                }
            }
            catch (Exception ex)
            {
                if (IsConnectionReset(ex))
                {
                    // Client disconnected gracefully — normal behavior
                    Log("Client disconnected (connection reset by peer)");
                }
                else
                {
                    Log(string.Format("HandleClient exception: {0}\n{1}", ex.Message, ex.StackTrace));
                }
            }
        }

        /// <summary>
        /// Determine if exception is client actively disconnecting
        /// </summary>
        private static bool IsConnectionReset(Exception ex)
        {
            // Check common client disconnect error codes
            if (ex.InnerException != null && ex.InnerException is System.Net.Sockets.SocketException)
            {
                var socketEx = (System.Net.Sockets.SocketException)ex.InnerException;
                // 10054 = WSAECONNRESET (remote host forcibly closed)
                // 10053 = WSAECONNABORTED (software caused connection abort)
                return socketEx.ErrorCode == 10054 || socketEx.ErrorCode == 10053;
            }
            return ex.Message.Contains("远程主机") || ex.Message.Contains("remote host") || ex.Message.Contains("connection was closed");
        }

        /// <summary>
        /// Process a JSON message (table lookup pattern)
        /// </summary>
        private string ProcessMessage(string json)
        {
            try
            {
                var method = JsonProtocol.ExtractMethod(json);
                var id = JsonProtocol.ExtractId(json);
                var rawParams = JsonProtocol.ExtractParams(json);

                if (string.IsNullOrEmpty(method))
                {
                    return JsonProtocol.Serialize(new ResponseMessage { Id = id, Error = "Missing method field" });
                }

                Log(string.Format("Received: {0} (id={1})", method, id));

                // Table lookup pattern
                if (!_methodHandlers.ContainsKey(method))
                {
                    return JsonProtocol.Serialize(new ResponseMessage
                    {
                        Id = id,
                        Error = string.Format("Unknown method: {0}. Supported: {1}", method, string.Join(", ", _methodHandlers.Keys))
                    });
                }

                // Marshal all handler calls to NX main thread
                // NXOpen API requires main thread execution, otherwise silent failure or crash
                Log(string.Format("[Dispatcher] Pre-dispatch check: IsInitialized={0}, method={1}",
                    MainThreadDispatcher.IsInitialized, method));
                string handlerResult = null;
                if (!MainThreadDispatcher.Invoke(() => {
                    Log(string.Format("[Dispatcher] >>> Execute on main thread: method={0}", method));
                    handlerResult = _methodHandlers[method](id, rawParams);
                    Log(string.Format("[Dispatcher] <<< Execution completed: method={0}", method));
                }))
                {
                    Log(string.Format("[Dispatcher] FAIL: Method {0} main thread dispatch failed", method));
                    return JsonProtocol.Serialize(new ResponseMessage
                    {
                        Id = id,
                        Error = string.Format("Method {0} main thread dispatch failed. Please check [Dispatcher] logs in tcp_server.log", method)
                    });
                }
                return handlerResult;
            }
            catch (Exception ex)
            {
                return JsonProtocol.Serialize(new ResponseMessage { Id = 0, Error = string.Format("Message processing exception: {0}", ex.Message) });
            }
        }

        // ================================================================
        // Method handlers
        // ================================================================

        private string HandlePing(int id, JToken rawParams)
        {
            return JsonProtocol.Serialize(new ResponseMessage
            {
                Id = id,
                Result = new
                {
                    pong = true,
                    timestamp = DateTime.UtcNow.ToString("o"),
                    version = PluginVersion.Full,
                    tool_count = _toolRegistry.ToolCount
                }
            });
        }

        private string HandleGetSelection(int id, JToken rawParams)
        {
            try
            {
                var objects = _monitor.GetSelection();
                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Result = new { objects, count = objects.Count }
                });
            }
            catch (Exception ex)
            {
                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Error = string.Format("Failed to get selection: {0}", ex.Message)
                });
            }
        }

        private string HandleGetModelSummary(int id, JToken rawParams)
        {
            try
            {
                var bodies = new List<ModelBodySummary>();
                try
                {
                    dynamic workPart = _session.Parts.Work;
                    if (workPart != null)
                    {
                        foreach (dynamic body in workPart.Bodies)
                        {
                            int faceCount = 0, edgeCount = 0;
                            try { dynamic faces = body.GetFaces(); faceCount = faces.Length; } catch { }
                            try { dynamic edges = body.GetEdges(); edgeCount = edges.Length; } catch { }
                            bodies.Add(new ModelBodySummary
                            {
                                Name = body.Name ?? "",
                                FaceCount = faceCount,
                                EdgeCount = edgeCount
                            });
                        }
                    }
                }
                catch { }
                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Result = new { bodies, count = bodies.Count }
                });
            }
            catch (Exception ex)
            {
                return JsonError(id, string.Format("Failed to get model summary: {0}", ex.Message));
            }
        }

        /// <summary>
        /// Execute tool — unified tool call interface
        ///
        /// Request format:
        ///   { "method": "tool", "id": 1, "params": { "tool": "nx_extrude", "distance": 10, ... } }
        ///
        /// Response format:
        ///   { "id": 1, "result": { "success": true, "message": "...", "data": {...} } }
        /// </summary>
        private string HandleTool(int id, JToken rawParams)
        {
            if (rawParams == null || !(rawParams is JObject))
                return JsonError(id, "Missing params field, must include tool name and parameters");

            try
            {
                var jObj = (JObject)rawParams;
                var toolName = jObj["tool"] != null ? jObj["tool"].Value<string>() : null;

                if (string.IsNullOrEmpty(toolName))
                    return JsonError(id, "Missing tool field in params");

                var tool = _toolRegistry.GetTool(toolName);
                if (tool == null)
                {
                    var toolNames = new List<string>(_toolRegistry.ListToolNames());
                    var available = string.Join(", ", toolNames.ToArray());
                    return JsonError(id, string.Format("Unknown tool: {0}. Available tools: {1}", toolName, available));
                }

                Log(string.Format("Execute tool: {0}, Dispatcher={1}", toolName, MainThreadDispatcher.IsInitialized));

                // Auto-inject user-selected face tags — resolves "selected face parameters not passed" issue
                // If caller did not explicitly provide face_tags or faces_to_remove, extract from current selection
                if (jObj["face_tags"] == null && jObj["faces_to_remove"] == null)
                {
                    var selection = _monitor.GetSelection();
                    var faceTags = new JArray();
                    foreach (var obj in selection)
                    {
                        if (obj.Type == "Face")
                            faceTags.Add(obj.Tag);
                    }
                    if (faceTags.Count > 0)
                    {
                        jObj["face_tags"] = faceTags;
                        Log(string.Format("Auto-injected {0} selected faces: {1}", faceTags.Count,
                            string.Join(",", faceTags.Select(t => t.Value<int>()))));
                    }
                }

                // ★ Work part guard (2026-09-10, M-005b) — see WorkPartGuard.cs
                //   Background: OpenBaseDisplay in probes/scripts can switch the work part away, causing subsequent tools
                //   to operate on the wrong part (previously caused false failures where tools returned empty results).
                //   Tools whose responsibility is "switch active part" are explicitly declared in ExemptTools; guard does not intervene.
                bool guardOn = !WorkPartGuard.IsExempt(toolName);

                // Dispatch tool execution to NX main thread — NXOpen API requires main thread execution
                JObject result = null;
                Rules.RuleValidateResult ruleResult = null;
                if (!MainThreadDispatcher.Invoke(() => {
                    Log(string.Format("[Dispatcher] >>> Execute tool on main thread: {0}", toolName));

                    // Snapshot — must be done on main thread (NXOpen API thread constraint)
                    // ★Stores both {Work, Display}: SetWork is only valid within display context (see WorkPartGuard class comments)
                    WorkPartGuard.Snapshot guardBefore = null;
                    if (guardOn)
                    {
                        string snapErr;
                        guardBefore = WorkPartGuard.Take((object)_session, out snapErr);
                        if (snapErr != null)
                            Log(string.Format("[WorkPartGuard] Snapshot failed, skipping guard this time: {0}", snapErr));
                    }

                    // Engineering rule check — before execution, on main thread (CheckFn may read NX geometry).
                    // Only record results, no interception here.
                    try
                    {
                        ruleResult = _rules.Validate(toolName, jObj);
                    }
                    catch (Exception rex)
                    {
                        Log(string.Format("[RuleEngine] Rule check exception, skipping this time: {0}", rex.Message));
                    }

                    result = tool.Execute(_session, jObj);

                    // Restore — only acts when work part was actually switched; zero overhead if untouched
                    if (guardOn && guardBefore != null && result != null)
                    {
                        JObject guardNote = WorkPartGuard.Restore((object)_session, guardBefore);
                        if (guardNote != null)
                        {
                            if (guardNote["restore_error"] != null)
                                Log(string.Format("[WorkPartGuard] ★Restore failed ({0}): {1}", toolName, guardNote["restore_error"]));
                            else
                                Log(string.Format("[WorkPartGuard] Restored work part: {0} -> {1} (tool {2} switched away{3})",
                                    guardNote["from"], guardNote["restored_to"], toolName,
                                    guardNote["display_restored_to"] != null
                                        ? ", display also restored to " + guardNote["display_restored_to"] : ""));
                            if (guardNote["display_restore_error"] != null)
                                Log(string.Format("[WorkPartGuard] ★Display restore failed ({0}): {1}", toolName, guardNote["display_restore_error"]));

                            // Report faithfully, not silently — contamination should be visible
                            JObject gdata = result["data"] as JObject;
                            if (gdata == null) { gdata = new JObject(); result["data"] = gdata; }
                            gdata["work_part_guard"] = guardNote;
                        }
                    }

                    Log(string.Format("[Dispatcher] <<< Tool execution completed: {0}, success={1}", toolName, result != null ? result["success"] : "null"));
                }))
                {
                    Log(string.Format("[Dispatcher] FAIL: Tool {0} main thread dispatch failed", toolName));
                    return JsonError(id, string.Format("Tool {0} execution failed: main thread dispatch failed. Please check [Dispatcher] logs in tcp_server.log", toolName));
                }

                Log(string.Format("Tool {0} execution completed: {1}", toolName, result["success"]));

                // Rule hints — attached as data.rule_check; error level also downgraded to hint, doesn't change success
                AttachRuleHints(result, ruleResult, toolName);

                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Result = result
                });
            }
            catch (Exception ex)
            {
                return JsonError(id, string.Format("Tool execution failed: {0}", ex.Message));
            }
        }

        /// <summary>
        /// Attach rule check results to result.data.rule_check.
        ///
        /// This method is the sole enforcement point for the "rules only hint" constraint:
        /// regardless of the rule verdict, it only writes data fields, returns void,
        /// and the caller never changes success or interrupts the flow based on this.
        ///
        /// Output shape:
        ///   data.rule_check = {
        ///     count:       number of reports (node omitted when 0)
        ///     issues:      [ "Hole edge clearance 1.2mm < 2x hole diameter 6.0mm", ... ]   ← error + warning combined
        ///     suggestions:     [ "Recommended clearance >= 6.0mm (2x diameter)", ... ]   ← optional
        ///     has_error_severity: true/false  ← whether an error-severity rule was hit.
        ///                          for callers to judge severity; this field triggers no interception.
        ///   }
        /// </summary>
        private void AttachRuleHints(JObject result, Rules.RuleValidateResult ruleResult, string toolName)
        {
            if (result == null || ruleResult == null)
                return;

            try
            {
                // Error level (Blockers) and warning level (Warnings) merged into same issues list —
                // to callers both are just "hints", no differentiated handling
                var issues = new JArray();
                foreach (var b in ruleResult.Blockers) issues.Add(b);
                foreach (var w in ruleResult.Warnings) issues.Add(w);

                if (issues.Count == 0 && ruleResult.Suggestions.Count == 0)
                    return;

                var gdata = result["data"] as JObject;
                if (gdata == null)
                {
                    gdata = new JObject();
                    result["data"] = gdata;
                }

                var rc = new JObject();
                rc["count"] = issues.Count;
                rc["issues"] = issues;
                if (ruleResult.Suggestions.Count > 0)
                    rc["suggestions"] = new JArray(ruleResult.Suggestions);
                rc["has_error_severity"] = ruleResult.Blockers.Count > 0;
                gdata["rule_check"] = rc;

                Log(string.Format("[RuleEngine] {0}: {1} hints (error-level {2})",
                    toolName, issues.Count, ruleResult.Blockers.Count));
            }
            catch (Exception ex)
            {
                // Hint error must never affect tool result — silently degrade to a log entry
                Log(string.Format("[RuleEngine] Failed to attach hint, ignored: {0}", ex.Message));
            }
        }

        /// <summary>
        /// List all available tools
        /// </summary>
        private string HandleListTools(int id, JToken rawParams)
        {
            try
            {
                var toolNames = _toolRegistry.ListToolNames();
                var toolList = new List<object>();
                foreach (var name in toolNames)
                {
                    var tool = _toolRegistry.GetTool(name);
                    if (tool != null)
                    {
                        toolList.Add(new { name = tool.Name, description = tool.Description });
                    }
                }

                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Result = new { tools = toolList, count = toolList.Count }
                });
            }
            catch (Exception ex)
            {
                return JsonError(id, string.Format("Failed to list tools: {0}", ex.Message));
            }
        }

        private string JsonError(int id, string message)
        {
            return JsonProtocol.Serialize(new ResponseMessage { Id = id, Error = message });
        }

        // ================================================================
        // NX object lookup helper methods — delegated to ToolHelpers (eliminate duplicate code)
        // ================================================================

        private dynamic FindBodyByTag(dynamic workPart, int tag)
        {
            return ToolHelpers.FindBodyByTag(workPart, tag);
        }

        private dynamic FindFaceByTag(dynamic workPart, int tag)
        {
            return ToolHelpers.FindFaceByTag(workPart, tag);
        }

        private dynamic FindEdgeByTag(dynamic workPart, int tag)
        {
            return ToolHelpers.FindEdgeByTag(workPart, tag);
        }

        // ================================================================
        // Extension methods — NX API implementations
        // ================================================================

        /// <summary>
        /// Measure area/volume/distance
        /// Corresponds to scenario 2: query model info
        ///
        /// Parameters:
        ///   measure_type — "area", "volume", "distance"
        ///   target_tag   — Target object tag (face/body/edge)
        ///   target_tag2  — Second target tag (only needed for distance)
        /// </summary>
        private string HandleMeasure(int id, JToken rawParams)
        {
            try
            {
                dynamic workPart = _session.Parts.Work;
                if (workPart == null)
                    return JsonError(id, "No active workpiece");

                string measureType = "area";
                int targetTag = 0;
                int targetTag2 = 0;

                if (rawParams is JObject)
                {
                    var jObj = (JObject)rawParams;
                    if (jObj["measure_type"] != null)
                        measureType = jObj["measure_type"].Value<string>().ToLower();
                    if (jObj["target_tag"] != null)
                        targetTag = jObj["target_tag"].Value<int>();
                    if (jObj["target_tag2"] != null)
                        targetTag2 = jObj["target_tag2"].Value<int>();
                }

                if (targetTag <= 0)
                    return JsonError(id, "Missing or invalid target_tag parameter");

                if (measureType == "area")
                {
                    // Measure face area: traverse body to find face matching tag, call face.GetArea()
                    dynamic face = FindFaceByTag(workPart, targetTag);
                    if (face == null)
                        return JsonError(id, string.Format("Face not found: tag={0}", targetTag));

                    double area = (double)face.GetArea();

                    return JsonProtocol.Serialize(new ResponseMessage
                    {
                        Id = id,
                        Result = new { measure_type = "area", value = area, unit = "mm^2", target_tag = targetTag }
                    });
                }
                else if (measureType == "volume")
                {
                    // Measure body volume: NX2412 GetMassProperties removed -> MeasureHelpers (GetBodyProperties/UF fallback)
                    dynamic body = FindBodyByTag(workPart, targetTag);
                    if (body == null)
                        return JsonError(id, string.Format("Solid not found: tag={0}", targetTag));

                    var mp = NxMcpPlugin.Tools.Measure.MeasureHelpers.GetBodyMassProps(_session, body);
                    double volume = mp.Volume;

                    return JsonProtocol.Serialize(new ResponseMessage
                    {
                        Id = id,
                        Result = new { measure_type = "volume", value = volume, unit = "mm^3", target_tag = targetTag }
                    });
                }
                else if (measureType == "distance")
                {
                    // Measure shortest distance between two objects: use MeasureManager.NewDistance
                    if (targetTag2 <= 0)
                        return JsonError(id, "Distance measurement needs target_tag2 parameter");

                    dynamic obj1 = FindFaceByTag(workPart, targetTag);
                    if (obj1 == null)
                        obj1 = FindEdgeByTag(workPart, targetTag);
                    if (obj1 == null)
                        return JsonError(id, string.Format("Object not found: tag={0}", targetTag));

                    dynamic obj2 = FindFaceByTag(workPart, targetTag2);
                    if (obj2 == null)
                        obj2 = FindEdgeByTag(workPart, targetTag2);
                    if (obj2 == null)
                        return JsonError(id, string.Format("Object not found: tag={0}", targetTag2));

                    // NX2412: MeasureManager.NewDistance requires unit parameter
                    dynamic lengthUnit = workPart.UnitCollection.FindObject("MilliMeter");
                    dynamic measure = workPart.MeasureManager.NewDistance(lengthUnit, obj1, obj2);
                    double distance = (double)measure.Value;

                    return JsonProtocol.Serialize(new ResponseMessage
                    {
                        Id = id,
                        Result = new
                        {
                            measure_type = "distance",
                            value = distance,
                            unit = "mm",
                            target_tag = targetTag,
                            target_tag2 = targetTag2
                        }
                    });
                }
                else
                {
                    return JsonError(id, string.Format("Unsupported measure_type: {0}. Supported: area, volume, distance", measureType));
                }
            }
            catch (Exception ex)
            {
                return JsonError(id, string.Format("Measurement failed: {0}", ex.Message));
            }
        }

        /// <summary>
        /// List feature tree
        /// Corresponds to scenario 2: query model info
        ///
        /// Parameters (optional):
        ///   feature_type — Filter by type (e.g. "Hole", "Extrude"), return all if empty
        /// </summary>
        private string HandleListFeatures(int id, JToken rawParams)
        {
            try
            {
                dynamic workPart = _session.Parts.Work;
                if (workPart == null)
                    return JsonError(id, "No active workpiece");

                string featureType = null;
                if (rawParams is JObject)
                {
                    var jObj = (JObject)rawParams;
                    if (jObj["feature_type"] != null)
                        featureType = jObj["feature_type"].Value<string>();
                }

                var features = new List<object>();
                int totalCount = 0;

                foreach (dynamic feature in workPart.Features)
                {
                    if (feature == null) continue;
                    totalCount++;

                    string fName = "";
                    string fType = "";
                    int fTag = 0;
                    try { fName = feature.FeatureName; } catch { }
                    try { fType = feature.FeatureType; } catch { }
                    try { fTag = (int)feature.Tag; } catch { }

                    // Filter by type
                    if (!string.IsNullOrEmpty(featureType))
                    {
                        if (fType == null || fType.IndexOf(featureType, StringComparison.OrdinalIgnoreCase) < 0)
                            continue;
                    }

                    features.Add(new
                    {
                        tag = fTag,
                        name = fName,
                        type = fType
                    });
                }

                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Result = new { features, count = features.Count, total = totalCount }
                });
            }
            catch (Exception ex)
            {
                return JsonError(id, string.Format("Failed to list features: {0}", ex.Message));
            }
        }

        /// <summary>
        /// Modify parameter expression
        /// Corresponds to scenario 6: parametric design
        ///
        /// Parameters:
        ///   expression_name — Expression name (e.g. "p0", "width")
        ///   new_value       — New value (numeric or string expression)
        /// </summary>
        private string HandleModifyExpression(int id, JToken rawParams)
        {
            try
            {
                dynamic workPart = _session.Parts.Work;
                if (workPart == null)
                    return JsonError(id, "No active workpiece");

                string expressionName = null;
                string newValue = null;

                if (rawParams is JObject)
                {
                    var jObj = (JObject)rawParams;
                    if (jObj["expression_name"] != null)
                        expressionName = jObj["expression_name"].Value<string>();
                    if (jObj["new_value"] != null)
                    {
                        var valToken = jObj["new_value"];
                        newValue = valToken.Type == JTokenType.String
                            ? valToken.Value<string>()
                            : valToken.ToString();
                    }
                }

                if (string.IsNullOrEmpty(expressionName))
                    return JsonError(id, "Missing expression_name parameter");

                if (string.IsNullOrEmpty(newValue))
                    return JsonError(id, "Missing new_value parameter");

                // Find expression
                dynamic expression = null;
                try
                {
                    expression = workPart.Expressions.FindObject(expressionName);
                }
                catch
                {
                    return JsonError(id, string.Format("Expression not found: {0}", expressionName));
                }

                if (expression == null)
                    return JsonError(id, string.Format("Expression not found: {0}", expressionName));

                // Save old value for return
                string oldValue = "";
                try { oldValue = expression.RightHandSide; } catch { }

                // Set new value
                expression.RightHandSide = newValue;

                // Update model (NX2412: Part.Update() doesn't exist, NX auto-updates expressions)
                try { workPart.Update(); } catch { }

                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Result = new
                    {
                        success = true,
                        expression_name = expressionName,
                        old_value = oldValue,
                        new_value = newValue
                    }
                });
            }
            catch (Exception ex)
            {
                return JsonError(id, string.Format("Failed to modify expression: {0}", ex.Message));
            }
        }

        /// <summary>
        /// Export STEP/IGES
        /// Corresponds to scenario 5: design iteration
        ///
        /// Parameters:
        ///   format    — "step" or "iges"
        ///   file_path — Export file full path
        /// </summary>
        private string HandleExport(int id, JToken rawParams)
        {
            try
            {
                dynamic workPart = _session.Parts.Work;
                if (workPart == null)
                    return JsonError(id, "No active workpiece");

                string format = "step";
                string filePath = null;

                if (rawParams is JObject)
                {
                    var jObj = (JObject)rawParams;
                    if (jObj["format"] != null)
                        format = jObj["format"].Value<string>().ToLower();
                    if (jObj["file_path"] != null)
                        filePath = jObj["file_path"].Value<string>();
                }

                if (string.IsNullOrEmpty(filePath))
                    return JsonError(id, "Missing file_path parameter");

                string lowerFormat = format != null ? format.ToLower() : "step";

                if (lowerFormat == "step")
                {
                    // STEP export: use DexManager (NX2412 standard method)
                    dynamic creator = _session.DexManager.CreateStepCreator();
                    try
                    {
                        creator.OutputFile = filePath;
                        creator.Apply();

                        return JsonProtocol.Serialize(new ResponseMessage
                        {
                            Id = id,
                            Result = new { success = true, format = "step", file_path = filePath }
                        });
                    }
                    finally
                    {
                        try { creator.Destroy(); } catch { }
                    }
                }
                else if (lowerFormat == "iges")
                {
                    // IGES export: use DexManager (NX2412 standard method)
                    dynamic creator = _session.DexManager.CreateIgesCreator();
                    try
                    {
                        creator.OutputFile = filePath;
                        creator.Apply();

                        return JsonProtocol.Serialize(new ResponseMessage
                        {
                            Id = id,
                            Result = new { success = true, format = "iges", file_path = filePath }
                        });
                    }
                    finally
                    {
                        try { creator.Destroy(); } catch { }
                    }
                }
                else
                {
                    return JsonError(id, string.Format("Unsupported export format: {0}. Supported: step, iges", format));
                }
            }
            catch (Exception ex)
            {
                return JsonError(id, string.Format("Export failed: {0}", ex.Message));
            }
        }

        /// <summary>
        /// Undo last step
        /// Corresponds to global function
        ///
        /// Use Session.Undo() to undo most recent visible UndoMark.
        /// No parameters needed.
        /// </summary>
        private string HandleUndo(int id, JToken rawParams)
        {
            try
            {
                Log("HandleUndo: Starting undo execution");
                Log(string.Format("HandleUndo: Session type = {0}", _session.GetType().FullName));

                // NX2412: Session.Undo() doesn't exist
                // Use UndoLastNVisibleMarks or UndoToLastVisibleMark instead
                bool marksRecycled;
                bool undoUnavailable;

                try
                {
                    Log("HandleUndo: Try UndoLastNVisibleMarks");
                    // Try 3-parameter version first (NX2412)
                    _session.UndoLastNVisibleMarks(1, out marksRecycled, out undoUnavailable);
                    Log(string.Format("HandleUndo: UndoLastNVisibleMarks succeeded, undoUnavailable={0}", undoUnavailable));
                    if (undoUnavailable)
                        return JsonError(id, "No operations to undo");
                }
                catch (Exception ex1)
                {
                    Log(string.Format("HandleUndo: UndoLastNVisibleMarks failed: {0}", ex1.Message));
                    Log("HandleUndo: Try UndoToLastVisibleMark");
                    // Fallback to UndoToLastVisibleMark (available since NX 3.0)
                    _session.UndoToLastVisibleMark();
                    Log("HandleUndo: UndoToLastVisibleMark succeeded");
                }

                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Result = new { success = true, message = "Last operation undone" }
                });
            }
            catch (Exception ex)
            {
                Log(string.Format("HandleUndo: Final exception: {0}", ex.ToString()));
                return JsonError(id, string.Format("Undo failed: {0}", ex.Message));
            }
        }

        /// <summary>
        /// Get expression list
        /// Corresponds to scenario 6: parametric design
        ///
        /// Parameters (optional):
        ///   name_filter — Filter by name (partial match), return all if empty
        /// </summary>
        private string HandleGetParameters(int id, JToken rawParams)
        {
            try
            {
                dynamic workPart = _session.Parts.Work;
                if (workPart == null)
                    return JsonError(id, "No active workpiece");

                string nameFilter = null;
                if (rawParams is JObject)
                {
                    var jObj = (JObject)rawParams;
                    if (jObj["name_filter"] != null)
                        nameFilter = jObj["name_filter"].Value<string>();
                }

                var expressions = new List<object>();

                foreach (dynamic expr in workPart.Expressions)
                {
                    if (expr == null) continue;

                    string eName = "";
                    string eValue = "";
                    string eUnits = "";

                    try { eName = expr.Name; } catch { }
                    try { eValue = expr.RightHandSide; } catch { }

                    // Get unit name
                    try
                    {
                        dynamic units = expr.Units;
                        if (units != null)
                            eUnits = units.Name;
                    }
                    catch { }

                    // Filter by name
                    if (!string.IsNullOrEmpty(nameFilter))
                    {
                        if (eName == null || eName.IndexOf(nameFilter, StringComparison.OrdinalIgnoreCase) < 0)
                            continue;
                    }

                    expressions.Add(new
                    {
                        name = eName,
                        value = eValue,
                        units = eUnits
                    });
                }

                return JsonProtocol.Serialize(new ResponseMessage
                {
                    Id = id,
                    Result = new { expressions, count = expressions.Count }
                });
            }
            catch (Exception ex)
            {
                return JsonError(id, string.Format("Failed to get expression list: {0}", ex.Message));
            }
        }

        /// <summary>
        /// Stop TCP service
        /// </summary>
        public void Stop()
        {
            _running = false;
            try { if (_listener != null) _listener.Stop(); } catch { }
            Log("TCP service stopped");
        }

        /// <summary>
        /// Log file maximum size (1MB) — auto-rotate when exceeded
        /// </summary>
        private const long MAX_LOG_SIZE = 1024 * 1024;

        /// <summary>
        /// Log rotation: rename current log to .1, create new log
        /// </summary>
        private void RotateLogIfNeeded(string logPath)
        {
            try
            {
                var fileInfo = new System.IO.FileInfo(logPath);
                if (fileInfo.Exists && fileInfo.Length > MAX_LOG_SIZE)
                {
                    var backupPath = logPath + ".1";
                    // Delete old backup
                    if (System.IO.File.Exists(backupPath))
                        System.IO.File.Delete(backupPath);
                    // Rename current log
                    System.IO.File.Move(logPath, backupPath);
                }
            }
            catch { }
        }

        private void Log(string msg)
        {
            // Production: NXOpen.LogFile.WriteLine(msg)
            // Development: Console.WriteLine
            System.Diagnostics.Debug.WriteLine(string.Format("[NxMcpPlugin] {0}", msg));
            Console.WriteLine(string.Format("[NxMcpPlugin] {0}", msg));
            // Also write to file for debugging
            try
            {
                var logPath = NxPaths.StartupFile("tcp_server.log");

                // Log rotation check
                RotateLogIfNeeded(logPath);

                System.IO.File.AppendAllText(logPath,
                    string.Format("[{0:HH:mm:ss.fff}] [TcpServer] {1}\n", DateTime.Now, msg));
            }
            catch { }
        }
    }
}
